package fr.sictiam.signature.pes.verifier;

public enum SignatureValidationError {
    INVALID_SCHEMA,
    INVALID_SIGNATURE,
    UNVERIFIABLE_SIGNATURE,
    NOT_SIGNED_CONTENT,
    SIGNATURE_CONTROL_ERRORS,
    ROLE_BLANK,
    DATE_BLANK,
    DATE_FORMAT_ERROR,
    XADES_ERROR,
    XADES_UPDATED,
    XADES_UNSIGNED,
    RECOMMENDATION_NOT_RESPECTED,
    CERTIFICAT_RECOGNITION_ERROR,
    UNTRUSTED_CERTIFICATE,
    WRONG_CERTIFICATE,
    XADES_EXCEPTION,
    POLICY_QUALIFIER_MISSING,
    NO_POLICY,
    POLICY_ID_MISSING

}
