version: '3'
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: stela
      POSTGRES_PASSWORD: stelapwd
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=test
     - RABBITMQ_DEFAULT_PASS=password
  config:
    image: stela-poc/config-service
    container_name: config
    ports:
     - "8888:8888"
    volumes:
     - ../stela-config:/stela-config
    depends_on:
     - postgresql
     - rabbitmq
    environment:
      - "SPRING_PROFILES_ACTIVE=native"
  discovery:
    image: stela-poc/discovery-service
    container_name: discovery
    ports:
     - "8761:8761"
  hystrix-dashboard:
    image: stela-poc/hystrix-dashboard
    container_name: hystrix-dashboard
    ports:
     - "7979:7979"
    depends_on:
     - config
     - discovery
    environment:
     - "SPRING_PROFILES_ACTIVE=prod"
  tracing-service:
    image: stela-poc/tracing-service
    container_name: tracing-service
    ports:
     - "9411:9411"
    depends_on:
     - config
     - discovery
     - rabbitmq
    environment:
     - "SPRING_PROFILES_ACTIVE=prod"
  api-gateway:
    image: stela-poc/api-gateway
    container_name: api-gateway
    ports:
     - "9004:9004"
    depends_on:
     - config
     - discovery
    environment:
     - "SPRING_PROFILES_ACTIVE=prod"
