version: '3'
services:
  clamav:
    image: mkodockx/docker-clamav:latest
    container_name: clamav
    ports:
     - "3310:3310"
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: stela
      POSTGRES_PASSWORD: stelapwd
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=test
     - RABBITMQ_DEFAULT_PASS=password
  config:
    image: stela-poc/config-service
    container_name: config
    ports:
     - "8888:8888"
    volumes:
     - ../stela-config:/stela-config
    environment:
      - "SPRING_PROFILES_ACTIVE=native"
  discovery:
    image: stela-poc/discovery-service
    container_name: discovery
    ports:
     - "8761:8761"
#  tracing-service:
#    image: openzipkin/zipkin
#    container_name: zipkin
#    ports:
#     - "9411:9411"
#    depends_on:
#     - config
#     - discovery
#     - rabbitmq
#    environment:
#     - "SPRING_PROFILES_ACTIVE=prod"
  api-gateway:
    image: stela-poc/api-gateway
    container_name: api-gateway
    ports:
     - "9004:9004"
    depends_on:
     - config
     - discovery
    environment:
     - "SPRING_PROFILES_ACTIVE=dev-docker"
  admin-service:
    image: stela-poc/admin-service
    container_name: admin-service
    ports:
     - "9006:9006"
    depends_on:
     - config
     - discovery
     - postgresql
     - rabbitmq
    environment:
     - "SPRING_PROFILES_ACTIVE=dev-docker"
  acte-service:
    image: stela-poc/acte-service
    container_name: acte-service
    ports:
     - "9008:9008"
    depends_on:
     - config
     - discovery
     - postgresql
     - rabbitmq
     - clamav
    environment:
     - "SPRING_PROFILES_ACTIVE=dev-docker"
    volumes:
        - ./../stela-config/certificates:/certificates
  pes-service:
    image: stela-poc/pes-service
    container_name: pes-service
    ports:
     - "9010:9010"
    depends_on:
     - config
     - discovery
     - postgresql
     - rabbitmq
    environment:
     - "SPRING_PROFILES_ACTIVE=dev-docker"
