version: '3'
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: stela
      POSTGRES_PASSWORD: stelapwd
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=test
     - RABBITMQ_DEFAULT_PASS=password
  config:
    image: stela-poc/config-service
    container_name: config
    ports:
     - "8888:8888"
    depends_on:
     - postgresql
     - rabbitmq
  discovery:
    image: stela-poc/discovery-service
    container_name: discovery
    ports:
     - "8761:8761"
  api-gateway:
    image: stela-poc/api-gateway
    container_name: api-gateway
    ports:
     - "9004:9004"
    depends_on:
     - config
     - discovery
    environment:
     - "SPRING_PROFILES_ACTIVE=integration"
  admin-service:
    image: stela-poc/admin-service
    container_name: admin-service
    ports:
     - "9006:9006"
    depends_on:
     - config
     - discovery
     - postgresql
    environment:
     - "SPRING_PROFILES_ACTIVE=integration"
  acte-service:
    image: stela-poc/acte-service
    container_name: acte-service
    ports:
     - "9008:9008"
    depends_on:
     - config
     - discovery
     - postgresql
    environment:
     - "SPRING_PROFILES_ACTIVE=integration"
  pes-service:
      image: stela-poc/pes-service
      container_name: pes-service
      ports:
       - "9009:9009"
      depends_on:
       - config
       - discovery
       - postgresql
       - rabbitmq
      environment:
       - "SPRING_PROFILES_ACTIVE=integration"  
