//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 03:18:09 PM CEST 
//

package fr.sictiam.stela.acteservice.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import java.time.LocalDate;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Nature">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *               &lt;pattern value="[0-9]{3}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Detail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ActeRecu" type="{http://www.interieur.gouv.fr/ACTES#v1.1-20040216}DonneesActe"/>
 *         &lt;element name="ClassificationDateVersionEnCours" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "date", "nature", "detail", "acteRecu", "classificationDateVersionEnCours" })
@XmlRootElement(name = "AnomalieActe")
public class AnomalieActe {

    @XmlElement(name = "Date", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1.class)
    @XmlSchemaType(name = "date")
    protected LocalDate date;
    @XmlElement(name = "Nature", required = true)
    @XmlJavaTypeAdapter(Adapter2.class)
    protected String nature;
    @XmlElement(name = "Detail")
    protected String detail;
    @XmlElement(name = "ActeRecu", required = true)
    protected DonneesActe acteRecu;
    @XmlElement(name = "ClassificationDateVersionEnCours", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1.class)
    @XmlSchemaType(name = "date")
    protected LocalDate classificationDateVersionEnCours;

    /**
     * Gets the value of the date property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public LocalDate getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDate(LocalDate value) {
        this.date = value;
    }

    /**
     * Gets the value of the nature property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNature() {
        return nature;
    }

    /**
     * Sets the value of the nature property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setNature(String value) {
        this.nature = value;
    }

    /**
     * Gets the value of the detail property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDetail() {
        return detail;
    }

    /**
     * Sets the value of the detail property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDetail(String value) {
        this.detail = value;
    }

    /**
     * Gets the value of the acteRecu property.
     * 
     * @return possible object is {@link DonneesActe }
     * 
     */
    public DonneesActe getActeRecu() {
        return acteRecu;
    }

    /**
     * Sets the value of the acteRecu property.
     * 
     * @param value
     *            allowed object is {@link DonneesActe }
     * 
     */
    public void setActeRecu(DonneesActe value) {
        this.acteRecu = value;
    }

    /**
     * Gets the value of the classificationDateVersionEnCours property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public LocalDate getClassificationDateVersionEnCours() {
        return classificationDateVersionEnCours;
    }

    /**
     * Sets the value of the classificationDateVersionEnCours property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setClassificationDateVersionEnCours(LocalDate value) {
        this.classificationDateVersionEnCours = value;
    }

}
