//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 03:18:09 PM CEST 
//

package fr.sictiam.stela.acteservice.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Matiere d'un acte (Code et libellé)
 * 
 * <p>
 * Java class for Matiere complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Matiere">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute ref="{http://www.interieur.gouv.fr/ACTES#v1.1-20040216}CodeMatiere use="required""/>
 *       &lt;attribute name="Libelle" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Matiere")
@XmlSeeAlso({
        fr.sictiam.stela.acteservice.model.xml.RetourClassification.Matieres.Matiere1.Matiere2.Matiere3.Matiere4.class,
        fr.sictiam.stela.acteservice.model.xml.RetourClassification.Matieres.Matiere1.Matiere2.Matiere3.class,
        fr.sictiam.stela.acteservice.model.xml.RetourClassification.Matieres.Matiere1.Matiere2.class,
        fr.sictiam.stela.acteservice.model.xml.RetourClassification.Matieres.Matiere1.class })
public class Matiere {

    @XmlAttribute(name = "CodeMatiere", namespace = "http://www.interieur.gouv.fr/ACTES#v1.1-20040216", required = true)
    @XmlJavaTypeAdapter(Adapter3.class)
    protected Integer codeMatiere;
    @XmlAttribute(name = "Libelle", namespace = "http://www.interieur.gouv.fr/ACTES#v1.1-20040216", required = true)
    protected String libelle;

    /**
     * Gets the value of the codeMatiere property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public Integer getCodeMatiere() {
        return codeMatiere;
    }

    /**
     * Sets the value of the codeMatiere property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCodeMatiere(Integer value) {
        this.codeMatiere = value;
    }

    /**
     * Gets the value of the libelle property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLibelle() {
        return libelle;
    }

    /**
     * Sets the value of the libelle property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLibelle(String value) {
        this.libelle = value;
    }

}
