//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 03:18:09 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.interieur.gouv.fr/ACTES#v1.1-20040216", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.sictiam.stela.acteservice.model.xml;
