//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.08 at 03:18:09 PM CEST 
//

package fr.sictiam.stela.acteservice.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Type de pièce jointe (Code et libellé)
 * 
 * <p>
 * Java class for TypePieceJointe complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="TypePieceJointe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="CodeTypePJ" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Libelle" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypePieceJointe")
public class TypePieceJointe {

    @XmlAttribute(name = "CodeTypePJ", namespace = "http://www.interieur.gouv.fr/ACTES#v1.1-20040216", required = true)
    protected String codeTypePJ;
    @XmlAttribute(name = "Libelle", namespace = "http://www.interieur.gouv.fr/ACTES#v1.1-20040216", required = true)
    protected String libelle;

    /**
     * Gets the value of the codeTypePJ property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCodeTypePJ() {
        return codeTypePJ;
    }

    /**
     * Sets the value of the codeTypePJ property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCodeTypePJ(String value) {
        this.codeTypePJ = value;
    }

    /**
     * Gets the value of the libelle property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLibelle() {
        return libelle;
    }

    /**
     * Sets the value of the libelle property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLibelle(String value) {
        this.libelle = value;
    }

}
