drop table if exists assembly_type_external_users cascade;
drop table if exists convocation_external_observer cascade;
drop table if exists convocation_response cascade;
drop table if exists convocation_response_question_responses cascade;
drop table if exists external_user cascade;
drop table if exists admin cascade;
drop table if exists assembly_type cascade;
drop table if exists assembly_type_recipient cascade;
drop table if exists attachment cascade;
drop table if exists convocation cascade;
drop table if exists convocation_annexes cascade;
drop table if exists convocation_histories cascade;
drop table if exists convocation_questions cascade;
drop table if exists convocation_recipients cascade;
drop table if exists convocation_history cascade;
drop table if exists question cascade;
drop table if exists question_response cascade;
drop table if exists question_responses cascade;
drop table if exists recipient cascade;
drop table if exists recipient_response cascade;
drop table if exists local_authority cascade ;

create table admin (uuid varchar(255) not null, alert_message varchar(255), alert_message_displayed boolean not null, primary key (uuid));
create table assembly_type_recipient (assembly_type_uuid varchar(255) not null, recipient_uuid varchar(255) not null, primary key (assembly_type_uuid, recipient_uuid));
create table assembly_type (uuid varchar(255) not null, active boolean, delay int4, inactivity_date timestamp, location varchar(255), name varchar(255), profile_uuid varchar(255), reminder boolean, use_procuration boolean, local_authority_uuid varchar(255), primary key (uuid));
create table attachment (uuid varchar(255) not null, date timestamp, filename varchar(255), size int8 not null, storage_key varchar(255), primary key (uuid));
create table convocation (uuid varchar(255) not null, comment varchar(255), creation_date timestamp, location varchar(255), meeting_date timestamp, profile_uuid varchar(255), subject varchar(255), assembly_type_uuid varchar(255), attachment_uuid varchar(255), local_authority_uuid varchar(255), primary key (uuid));
create table convocation_annexes (convocation_uuid varchar(255) not null, annexes_uuid varchar(255) not null, primary key (convocation_uuid, annexes_uuid));
create table convocation_histories (convocation_uuid varchar(255) not null, histories_uuid varchar(255) not null, primary key (convocation_uuid, histories_uuid));
create table convocation_questions (convocation_uuid varchar(255) not null, questions_uuid varchar(255) not null, primary key (convocation_uuid, questions_uuid));
create table convocation_recipients (convocation_uuid varchar(255) not null, recipients_uuid varchar(255) not null, primary key (convocation_uuid, recipients_uuid));
create table convocation_history (uuid varchar(255) not null, date timestamp, message varchar(1024), status varchar(255), attachment_uuid varchar(255), convocation_uuid varchar(255), primary key (uuid));
create table local_authority (uuid varchar(255) not null, active boolean, name varchar(255), resident_threshold boolean, siren varchar(255), slug_name varchar(255), primary key (uuid));
create table question (uuid varchar(255) not null, question varchar(255), primary key (uuid));
create table question_responses (question_uuid varchar(255) not null, responses_uuid varchar(255) not null, primary key (question_uuid, responses_uuid));
create table question_response (uuid varchar(255) not null, response boolean, question_uuid varchar(255), primary key (uuid));
create table recipient (uuid varchar(255) not null, active boolean, additional_contact boolean, email varchar(255), firstname varchar(255), inactivity_date timestamp, lastname varchar(255), phone_number varchar(255), token varchar(255), local_authority_uuid varchar(255), primary key (uuid));
create table recipient_response (uuid varchar(255) not null, open_date timestamp, opened boolean not null, response_type varchar(255), convocation_uuid varchar(255), recipient_uuid varchar(255), substitute_recipient_uuid varchar(255), primary key (uuid));
alter table if exists convocation_annexes add constraint UK_atdqli5lbh7xeoja6dv162sx8 unique (annexes_uuid);
alter table if exists convocation_histories add constraint UK_qpmrhmel836lf3jicpl7vp5wb unique (histories_uuid);
alter table if exists convocation_questions add constraint UK_nb79i0asd223kbjo0n28lpyg2 unique (questions_uuid);
alter table if exists question_responses add constraint UK_ixe3y2km4j2vj1ribxee0fkpb unique (responses_uuid);
alter table if exists assembly_type_recipient add constraint FK8gfonchbjegmvh7e6xd6daur5 foreign key (recipient_uuid) references recipient;
alter table if exists assembly_type_recipient add constraint FKpldw92g17hsjhc9ruf79ewk45 foreign key (assembly_type_uuid) references assembly_type;
alter table if exists assembly_type add constraint FKb086693dw4c2kjh25cqxqb1ra foreign key (local_authority_uuid) references local_authority;
alter table if exists convocation add constraint FK9fvthp33qkg1lfkpcvntj98s3 foreign key (assembly_type_uuid) references assembly_type;
alter table if exists convocation add constraint FKk45anwhkdihwuqvm4nrsawy11 foreign key (attachment_uuid) references attachment;
alter table if exists convocation add constraint FKq9ld60bsu3ymd7e3ldfwcnjr1 foreign key (local_authority_uuid) references local_authority;
alter table if exists convocation_annexes add constraint FKbe1dnyo0mlbm1ye99xh06lsga foreign key (annexes_uuid) references attachment;
alter table if exists convocation_annexes add constraint FKtoj1siayae5sbu3knh6kqvve0 foreign key (convocation_uuid) references convocation;
alter table if exists convocation_histories add constraint FKc2fjo1qag11n86niprhvfvcwh foreign key (histories_uuid) references convocation_history;
alter table if exists convocation_histories add constraint FK891fwg8pe5b6fq6g0cywrekdw foreign key (convocation_uuid) references convocation;
alter table if exists convocation_questions add constraint FKaa3vq524ra0t12ifyn762r0p4 foreign key (questions_uuid) references question;
alter table if exists convocation_questions add constraint FKavm7od5b0mxxswllvm594aw5f foreign key (convocation_uuid) references convocation;
alter table if exists convocation_recipients add constraint FKgkogg7tlhaxyafmltajvguo1j foreign key (recipients_uuid) references recipient;
alter table if exists convocation_recipients add constraint FKfrwmiv6x908jj2o87qt4w0wq0 foreign key (convocation_uuid) references convocation;
alter table if exists convocation_history add constraint FK71twpbrlat87foodaebryolir foreign key (attachment_uuid) references attachment;
alter table if exists convocation_history add constraint FK6n00ta7y97u70s17bgna109iy foreign key (convocation_uuid) references convocation;
alter table if exists question_responses add constraint FKtkak9til4yylhux4dad441jbq foreign key (responses_uuid) references question_response;
alter table if exists question_responses add constraint FKaxctj3rtmeej5wy8npxorlcas foreign key (question_uuid) references question;
alter table if exists question_response add constraint FKn771wco9pbgfql47cg65fu60q foreign key (question_uuid) references question;
alter table if exists recipient add constraint FKfacjg88ek7fe09pg7xt2p1xwm foreign key (local_authority_uuid) references local_authority;
alter table if exists recipient_response add constraint FKj38odc8wqrn5kc0ri0naiidjm foreign key (convocation_uuid) references convocation;
alter table if exists recipient_response add constraint FK676betlrscu6kv82j6vs2135c foreign key (recipient_uuid) references recipient;
alter table if exists recipient_response add constraint FK5gtrpr9prwcyx5qh370jfwnqw foreign key (substitute_recipient_uuid) references recipient;
