package fr.sictiam.stela.acteservice.model;

public enum StatusType {
    CREATED("CREATED", false),
    RECREATED("RECREATED", false),
    ARCHIVE_CREATED("ARCHIVE_CREATED", false),
    ANTIVIRUS_OK("ANTIVIRUS_OK", false),
    ANTIVIRUS_KO("ANTIVIRUS_KO", true),
    SENT("SENT", false),
    NOT_SENT("NOT_SENT", true),
    ACK_RECEIVED("ACK_RECEIVED", false),
    NACK_RECEIVED("NACK_RECEIVED", true),
    CANCELLATION_ASKED("CANCELLATION_ASKED", false),
    CANCELLATION_ARCHIVE_CREATED("CANCELLATION_ARCHIVE_CREATED", false),
    CANCELLED("CANCELLED", false),
    ARCHIVE_TOO_LARGE("ARCHIVE_TOO_LARGE", true),
    ARCHIVE_SIZE_CHECKED("ARCHIVE_SIZE_CHECKED", false),
    FILE_ERROR("FILE_ERROR", true),
    NOTIFICATION_SENT("NOTIFICATION_SENT", false),
    GROUP_NOTIFICATION_SENT("GROUP_NOTIFICATION_SENT", false),
    COURRIER_SIMPLE_RECEIVED("COURRIER_SIMPLE_RECEIVED", false),
    DEMANDE_PIECE_COMPLEMENTAIRE_RECEIVED("DEMANDE_PIECE_COMPLEMENTAIRE_RECEIVED", false),
    LETTRE_OBSERVATION_RECEIVED("LETTRE_OBSERVATION_RECEIVED", false),
    DEFERE_RECEIVED("DEFERE_RECEIVED", false),
    REPONSE_LETTRE_OBSEVATION_ASKED("REPONSE_LETTRE_OBSEVATION_ASKED", false),
    REJET_LETTRE_OBSERVATION_ASKED("REJET_LETTRE_OBSERVATION_ASKED", false),
    REFUS_PIECES_COMPLEMENTAIRE_ASKED("REFUS_PIECES_COMPLEMENTAIRE_ASKED", false),
    PIECE_COMPLEMENTAIRE_ASKED("PIECE_COMPLEMENTAIRE_ASKED", false),
    REPONSE_COURRIER_SIMPLE_ASKED("REPONSE_COURRIER_SIMPLE_ASKED", false),
    ACK_REPONSE_PIECE_COMPLEMENTAIRE("ACK_PIECE_COMPLEMENTAIRE", false),
    ACK_REPONSE_LETTRE_OBSERVATION("ACK_LETTRE_OBSERVATION", false),
    SIGNATURE_ERROR("SIGNATURE_ERROR", true),
    SENT_TO_SAE("SENT_TO_SAE", false),
    ACCEPTED_BY_SAE("ACCEPTED_BY_SAE", false);

    final String name;
    final boolean anomaly;

    StatusType(String s, boolean anomaly) {
        name = s;
        this.anomaly = anomaly;
    }

    public boolean isAnomaly() {
        return this.anomaly;
    }

    @Override
    public String toString() {
        return this.name;
    }
}
