package fr.sictiam.stela.acteservice.model;

public enum StatusType {
    CREATED("CREATED"),
    ARCHIVE_CREATED("ARCHIVE_CREATED"),
    ANTIVIRUS_OK("ANTIVIRUS_OK"),
    ANTIVIRUS_KO("ANTIVIRUS_KO"),
    SENT("SENT"),
    NOT_SENT("NOT_SENT"),
    ACK_RECEIVED("ACK_RECEIVED"),
    NACK_RECEIVED("NACK_RECEIVED"),
    CANCELLATION_ASKED("CANCELLATION_ASKED"),
    CANCELLATION_ARCHIVE_CREATED("CANCELLATION_ARCHIVE_CREATED"),
    CANCELLED("CANCELLED"),
    ARCHIVE_TOO_LARGE("ARCHIVE_TOO_LARGE"),
    ARCHIVE_SIZE_CHECKED("ARCHIVE_SIZE_CHECKED"),
    FILE_ERROR("FILE_ERROR"),
    NOTIFICATION_SENT("NOTIFICATION_SENT"),
    GROUP_NOTIFICATION_SENT("GROUP_NOTIFICATION_SENT"),
    COURRIER_SIMPLE_RECEIVED("COURRIER_SIMPLE_RECEIVED"),
    DEMANDE_PIECE_COMPLEMENTAIRE_RECEIVED("DEMANDE_PIECE_COMPLEMENTAIRE_RECEIVED"),
    LETTRE_OBSERVATION_RECEIVED("LETTRE_OBSERVATION_RECEIVED"),
    DEFERE_RECEIVED("DEFERE_RECEIVED"),
    REJET_LETTRE_OBSERVATION_ARCHIVE_CREATED("REJET_LETTRE_OBSERVATION_ARCHIVE_CREATED"),
    REFUS_PIECES_COMPLEMENTAIRE_ARCHIVE_CREATED("REFUS_PIECES_COMPLEMENTAIRE_ARCHIVE_CREATED"),
    PIECE_COMPLEMENTAIRE_ARCHIVE_CREATED("PIECE_COMPLEMENTAIRE_ARCHIVE_CREATED"),
    REPONSE_LETTRE_OBSERVATION_ARCHIVE_CREATED("REPONSE_LETTRE_OBSERVATION_ARCHIVE_CREATED"),
    REPONSE_COURRIER_SIMPLE_ARCHIVE_CREATED("REPONSE_COURRIER_SIMPLE_ARCHIVE_CREATED"),
    ACK_LETTRE_OBSERVATION_ARCHIVE_CREATED("ACK_LETTRE_OBSERVATION_ARCHIVE_CREATED"),
    ACK_PIECE_COMPLEMENTAIRE_ARCHIVE_CREATED("ACK_PIECE_COMPLEMENTAIRE_ARCHIVE_CREATED"),
    REPONSE_LETTRE_OBSEVATION_ASKED("REPONSE_LETTRE_OBSEVATION_ASKED"),
    REJET_LETTRE_OBSERVATION_ASKED("REJET_LETTRE_OBSERVATION_ASKED"),
    REFUS_PIECES_COMPLEMENTAIRE_ASKED("REFUS_PIECES_COMPLEMENTAIRE_ASKED"),
    PIECE_COMPLEMENTAIRE_ASKED("PIECE_COMPLEMENTAIRE_ASKED"),
    REPONSE_COURRIER_SIMPLE_ASKED("REPONSE_COURRIER_SIMPLE_ASKED"),
    ACK_REPONSE_PIECE_COMPLEMENTAIRE("ACK_PIECE_COMPLEMENTAIRE"),
    ACK_REPONSE_LETTRE_OBSERVATION("ACK_LETTRE_OBSERVATION");

    final String name;

    StatusType(String s) {
        name = s;
    }

    @Override
    public String toString() {
        return this.name;
    }
}
