package fr.sictiam.stela.convocationservice.model;

public enum NotificationType {
    CONVOCATION_CREATED,
    CONVOCATION_UPDATED,
    CONVOCATION_CANCELLED,
    PROCURATION_RECEIVED,
    PROCURATION_CANCELLED,
    MINUTES_ADDED,
    CONVOCATION_READ,
    CONVOCATION_RESPONSE,
    CONVOCATION_REMINDER,
    NO_RESPONSE_INFO
}
